/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import Controller.Controller;

/**
 *
 * @author Joe
 */
public class AddNewNotificationView extends javax.swing.JDialog {
    
    private Controller controller = null;

    /**
     * Creates new form AddNewNotificationView
     */
    public AddNewNotificationView(java.awt.Frame parent, boolean modal, Controller controller) {
        super(parent, modal);
        this.controller = controller;
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        descriptionTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        plotComboBox = new javax.swing.JComboBox<>();
        closeButton = new javax.swing.JButton();
        createButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(4, 2, 10, 10));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Add New Notification");
        getContentPane().add(jLabel1);
        getContentPane().add(jLabel2);

        jLabel3.setText("Location");
        getContentPane().add(jLabel3);
        getContentPane().add(descriptionTextField);

        jLabel4.setText("Plot");
        getContentPane().add(jLabel4);

        plotComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Birdhouse", "Fruit Tree Allotment", "Tree Allotment", "Seaweed Allotment", "Herb Allotment", " " }));
        getContentPane().add(plotComboBox);

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(closeButton);

        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        getContentPane().add(createButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        String location = "Low";
        if (this.plotComboBox.getSelectedIndex() == 0){
            location =  "High";
        }
        this.controller.addNotification(this.descriptionTextField.getText(), location);
        System.out.println("There are " + this.controller.getModel().getSize() + " task(s) on the list");
    }//GEN-LAST:event_createButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JButton createButton;
    private javax.swing.JTextField descriptionTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> plotComboBox;
    // End of variables declaration//GEN-END:variables
}
